spring:
application:
name: contact-service
data:
mongodb:
uri: mongodb://admin:admin123@mongodb:27017/easybulk_contacts?authSource=admin
auto-index-creation: true
servlet:
multipart:
max-file-size: 30MB
max-request-size: 30MB

server:
port: 8084

jwt:
secret: ${JWT_SECRET:3zf52MgZ/DhJJl8o+tVSs7FN3AVuEYGC0/zx9CvKjdwPlfr91HoTvm9xOk/EhHe1}
expiration: ${JWT_EXPIRATION:86400000}
refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

logging:
level:
com.easybulk: DEBUG

